# Generated by Django 5.2.2 on 2026-01-30 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_khach_hang', models.CharField(max_length=255)),
                ('ma_so_thue', models.CharField(blank=True, max_length=20, unique=True)),
                ('dia_chi', models.CharField(blank=True, max_length=255)),
                ('phan_loai', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('phai_thu_dau_ky', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('phai_tra_dau_ky', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_hoa_don', models.CharField(max_length=50)),
                ('ngay_hd', models.DateField(null=True)),
                ('hinh_thuc_tt', models.CharField(blank=True, max_length=100)),
                ('mau_so', models.CharField(blank=True, max_length=50)),
                ('ky_hieu', models.CharField(blank=True, max_length=50)),
                ('ten_dv_ban', models.CharField(max_length=200)),
                ('ma_so_thue', models.CharField(max_length=50)),
                ('dia_chi', models.TextField(blank=True)),
                ('ten_nguoi_mua', models.CharField(blank=True, max_length=200)),
                ('ma_so_thue_mua', models.CharField(blank=True, max_length=50)),
                ('dia_chi_mua', models.TextField(blank=True)),
                ('so_tk', models.CharField(blank=True, max_length=100)),
                ('ten_ngan_hang', models.CharField(blank=True, max_length=100)),
                ('tong_tien_hang', models.FloatField(default=0)),
                ('tong_tien_thue', models.FloatField(default=0)),
                ('tong_tien', models.DecimalField(decimal_places=2, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('xml_uuid', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('loai_hd', models.CharField(choices=[('VAO', 'Hóa đơn vào'), ('XUAT', 'Hóa đơn xuất')], default='VAO', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ProductName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=100, null=True)),
                ('ten_hang', models.CharField(max_length=255)),
                ('ten_goi_chung', models.CharField(blank=True, max_length=255, null=True)),
                ('ten_goi_xuat', models.CharField(blank=True, max_length=255, null=True)),
                ('nhom_hang', models.CharField(blank=True, choices=[('son_nuoc', 'Sơn nước'), ('son_dau', 'Sơn dầu'), ('chat_mau', 'Chất màu'), ('chong_tham', 'Chống thấm')], max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_dv_ban', models.CharField(max_length=200)),
                ('ma_so_thue', models.CharField(max_length=50, unique=True)),
                ('dia_chi', models.TextField(blank=True)),
                ('phan_loai', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(max_length=50, unique=True)),
                ('is_export', models.BooleanField(default=False)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_tax', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('phan_loai_phieu', models.CharField(choices=[('HH', 'Hàng hóa'), ('PX', 'Phiếu xuất'), ('KH', 'Khác')], default='HH', max_length=2, verbose_name='Phân loại phiếu')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoice_reader_app.customer')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='invoice_reader_app.invoice')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoice_reader_app.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='BankPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('debit', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('credit', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('balance', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('doc_no', models.CharField(blank=True, max_length=255)),
                ('stt', models.CharField(blank=True, max_length=50)),
                ('content', models.TextField(blank=True, null=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('is_summary', models.BooleanField(default=False)),
                ('bank_doc_no', models.CharField(blank=True, max_length=255)),
                ('related_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='summaries', to='invoice_reader_app.bankpayment')),
                ('purchase_orders', models.ManyToManyField(blank=True, to='invoice_reader_app.purchaseorder')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('so_luong_quy_doi', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('thue_suat_field', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('tien_thue_field', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sku', models.CharField(blank=True, max_length=100, null=True)),
                ('ten_goi_chung', models.CharField(blank=True, max_length=200, null=True)),
                ('is_export', models.BooleanField(default=False)),
                ('chiet_khau', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('thanh_tien_sau_ck', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('thanh_toan_field', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('thanh_tien', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoice_reader_app.purchaseorder')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_hang', models.CharField(max_length=200)),
                ('sku', models.CharField(blank=True, max_length=100, null=True)),
                ('dvt', models.CharField(max_length=200)),
                ('so_luong', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('don_gia', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('thanh_tien', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('thue_suat', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('tien_thue', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('thanh_toan', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('chiet_khau', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('ten_goi_xuat', models.CharField(blank=True, max_length=255, null=True)),
                ('ten_goi_chung', models.CharField(blank=True, max_length=255, null=True)),
                ('active', models.BooleanField(default=True)),
                ('po_item_id', models.IntegerField(blank=True, null=True)),
                ('nhom_hang', models.CharField(blank=True, choices=[('son_nuoc', 'Sơn nước'), ('son_dau', 'Sơn dầu'), ('chat_mau', 'Chất màu'), ('chong_tham', 'Chống thấm')], max_length=50, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoice_reader_app.customer')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoice_reader_app.invoice')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoice_reader_app.supplier')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoice_reader_app.supplier'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(fields=('so_hoa_don', 'ky_hieu', 'ma_so_thue', 'ngay_hd', 'loai_hd'), name='uniq_invoice_full'),
        ),
    ]
