# Generated by Django 5.2.7 on 2025-10-30 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_hoa_don', models.CharField(max_length=50)),
                ('ngay_hd', models.CharField(max_length=20)),
                ('hinh_thuc_tt', models.CharField(blank=True, max_length=100)),
                ('mau_so', models.CharField(blank=True, max_length=50)),
                ('ky_hieu', models.CharField(blank=True, max_length=50)),
                ('ten_dv_ban', models.CharField(max_length=200)),
                ('ma_so_thue', models.CharField(max_length=50)),
                ('dia_chi', models.TextField(blank=True)),
                ('ten_nguoi_mua', models.CharField(blank=True, max_length=200)),
                ('ma_so_thue_mua', models.CharField(blank=True, max_length=50)),
                ('dia_chi_mua', models.TextField(blank=True)),
                ('so_tk', models.CharField(blank=True, max_length=100)),
                ('ten_ngan_hang', models.CharField(blank=True, max_length=100)),
                ('tong_tien', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('phan_loai', models.CharField(choices=[('hang_hoa', 'Cung cấp hàng hóa'), ('dich_vu', 'Cung cấp dịch vụ'), ('khac', 'Khác')], default='hang_hoa', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_dv_ban', models.CharField(max_length=200)),
                ('ma_so_thue', models.CharField(max_length=50, unique=True)),
                ('dia_chi', models.TextField(blank=True)),
                ('phan_loai', models.CharField(choices=[('hang_hoa', 'Cung cấp hàng hóa'), ('dich_vu', 'Cung cấp dịch vụ'), ('khac', 'Khác')], default='hang_hoa', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_hang', models.CharField(max_length=200)),
                ('dvt', models.CharField(max_length=50)),
                ('so_luong', models.FloatField()),
                ('don_gia', models.FloatField()),
                ('thanh_tien', models.FloatField()),
                ('thue_suat', models.CharField(blank=True, max_length=20)),
                ('tien_thue', models.FloatField()),
                ('thanh_toan', models.FloatField()),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoice_reader_app.invoice')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='invoice_reader_app.supplier'),
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together={('so_hoa_don', 'ky_hieu', 'mau_so', 'ma_so_thue')},
        ),
    ]
