# Generated by Django 5.2.2 on 2026-08-28 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_reader_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryOpening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(db_index=True, max_length=100)),
                ('ten_goi_chung', models.CharField(blank=True, default='', max_length=255)),
                ('unit', models.CharField(blank=True, default='', max_length=50)),
                ('so_luong', models.FloatField(default=0)),
                ('don_gia', models.FloatField(default=0)),
                ('thanh_tien', models.FloatField(default=0)),
                ('ngay', models.DateField(blank=True, null=True)),
                ('ghi_chu', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
