# Generated by Django 5.2.2 on 2026-01-31 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_reader_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='invoice',
            name='uniq_invoice_full',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='xml_uuid',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['ma_so_thue', 'ky_hieu', 'so_hoa_don'], name='invoice_rea_ma_so_t_5e293c_idx'),
        ),
    ]
