# Generated by Django 5.2.2 on 2026-02-01 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_reader_app', '0002_remove_invoice_uniq_invoice_full_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
