# Generated by Django 5.2.7 on 2025-10-30 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_reader_app', '0002_alter_invoice_supplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='phan_loai',
        ),
    ]
