# Generated by Django 5.2.2 on 2026-08-30 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_reader_app', '0002_inventoryopening'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryopening',
            name='unit',
        ),
        migrations.AddField(
            model_name='inventoryopening',
            name='dvt',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
