# Generated by Django 5.2.2 on 2025-12-04 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_reader_app', '0002_purchaseorder_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='is_export',
            field=models.BooleanField(default=False),
        ),
    ]
