# Generated by Django 5.2.2 on 2025-10-30 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_reader_app', '0003_remove_invoice_phan_loai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='invoice_reader_app.supplier'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phan_loai',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
