# Generated by Django 5.2.2 on 2026-08-30 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_reader_app', '0003_remove_inventoryopening_unit_inventoryopening_dvt'),
    ]

    operations = [
        migrations.AddField(
            model_name='productname',
            name='dvt',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
