# Generated by Django 5.2.2 on 2026-02-01 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_reader_app', '0003_invoice_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='trang_thai',
            field=models.CharField(choices=[('CHO_XUAT', 'Chờ xuất hóa đơn'), ('DA_XUAT', 'Đã xuất hóa đơn')], default='CHO_XUAT', max_length=20),
        ),
    ]
