# Generated by Django 5.2.7 on 2025-12-23 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_reader_app', '0003_purchaseorder_is_export'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='tong_tien',
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
    ]
