# Generated by Django 5.2.2 on 2025-10-30 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_reader_app', '0004_alter_invoice_supplier_alter_supplier_phan_loai'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoice_reader_app.supplier'),
        ),
    ]
