# Generated by Django 5.2.2 on 2025-12-23 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_reader_app', '0004_alter_invoice_tong_tien'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankpayment',
            name='is_summary',
            field=models.BooleanField(default=False),
        ),
    ]
