# Generated by Django 5.2.7 on 2026-02-02 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_reader_app', '0004_invoice_trang_thai'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='fiscal_year',
            field=models.IntegerField(db_index=True, null=True),
        ),
    ]
