# Generated by Django 5.2.2 on 2026-09-12 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_reader_app', '0004_productname_dvt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Hãng')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang sử dụng')),
            ],
            options={
                'verbose_name': 'Hãng',
                'verbose_name_plural': 'Hãng',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Loại hàng')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang sử dụng')),
            ],
            options={
                'verbose_name': 'Loại hàng',
                'verbose_name_plural': 'Loại hàng',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Phân loại')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang sử dụng')),
            ],
            options={
                'verbose_name': 'Phân loại hàng',
                'verbose_name_plural': 'Phân loại hàng',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='productname',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='invoice_reader_app.brand', verbose_name='Hãng'),
        ),
        migrations.AddField(
            model_name='productname',
            name='product_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='invoice_reader_app.productlevel', verbose_name='Loại hàng'),
        ),
        migrations.AddField(
            model_name='productname',
            name='product_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='invoice_reader_app.producttype', verbose_name='Phân loại'),
        ),
    ]
