# Generated by Django 5.2.2 on 2025-10-30 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_reader_app', '0005_invoiceitem_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='loai_hd',
            field=models.CharField(choices=[('VAO', 'Hóa đơn vào'), ('XUAT', 'Hóa đơn xuất')], default='VAO', max_length=10),
        ),
    ]
