# Generated by Django 5.2.7 on 2025-12-24 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_reader_app', '0005_bankpayment_is_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phai_thu_dau_ky',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='customer',
            name='phai_tra_dau_ky',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
    ]
