# Generated by Django 5.2.2 on 2026-09-14 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_reader_app', '0005_brand_productlevel_producttype_productname_brand_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=20, unique=True, verbose_name='Biển số xe')),
                ('vehicle_type', models.CharField(blank=True, max_length=100, verbose_name='Loại xe')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='Nhãn hiệu')),
                ('model', models.CharField(blank=True, max_length=100, verbose_name='Model')),
                ('color', models.CharField(blank=True, max_length=50, verbose_name='Màu xe')),
                ('load_capacity', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Tải trọng (kg)')),
                ('total_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Trọng lượng toàn bộ (kg)')),
                ('passenger_capacity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Số người được phép chở')),
                ('chassis_number', models.CharField(blank=True, max_length=100, verbose_name='Số khung')),
                ('engine_number', models.CharField(blank=True, max_length=100, verbose_name='Số máy')),
                ('manufacture_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Năm sản xuất')),
                ('put_into_use_date', models.DateField(blank=True, null=True, verbose_name='Ngày đưa vào sử dụng')),
                ('inspection_number', models.CharField(blank=True, max_length=100, verbose_name='Số đăng kiểm')),
                ('inspection_date', models.DateField(blank=True, null=True, verbose_name='Ngày đăng kiểm')),
                ('inspection_expiry', models.DateField(blank=True, null=True, verbose_name='Hạn đăng kiểm')),
                ('badge_number', models.CharField(blank=True, max_length=100, verbose_name='Số phù hiệu')),
                ('badge_expiry', models.DateField(blank=True, null=True, verbose_name='Hạn phù hiệu')),
                ('status', models.CharField(choices=[('active', 'Đang sử dụng'), ('inactive', 'Tạm ngưng'), ('disposed', 'Thanh lý')], default='active', max_length=20, verbose_name='Trạng thái')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Phương tiện vận tải',
                'verbose_name_plural': 'Phương tiện vận tải',
                'db_table': 'vehicles',
                'ordering': ['license_plate'],
            },
        ),
    ]
