# Generated by Django 5.2.2 on 2025-12-26 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_reader_app', '0006_customer_phai_thu_dau_ky_customer_phai_tra_dau_ky'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankpayment',
            name='bank_doc_no',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
