# Generated by Django 5.2.2 on 2025-10-30 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_reader_app', '0006_invoice_loai_hd'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_khach_hang', models.CharField(max_length=255)),
                ('ma_so_thue', models.CharField(blank=True, max_length=20)),
                ('dia_chi', models.CharField(blank=True, max_length=255)),
                ('phan_loai', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
        ),
    ]
