# Generated by Django 5.2.2 on 2026-09-14 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_reader_app', '0006_vehicle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicle',
            options={'ordering': ['license_plate'], 'verbose_name': 'Phương tiện', 'verbose_name_plural': 'Phương tiện'},
        ),
        migrations.AddField(
            model_name='vehicle',
            name='cargo_dimensions',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Kích thước lòng / bao thùng xe'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='carries_explosives',
            field=models.BooleanField(default=False, verbose_name='Vận chuyển vật liệu nổ'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='commercial_use',
            field=models.BooleanField(default=False, verbose_name='Có kinh doanh vận tải'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='curb_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Khối lượng bản thân'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='drive_configuration',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Công thức bánh xe'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='emission_level',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Mức khí thải'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='engine_displacement',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Thể tích làm việc'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='engine_model',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ký hiệu động cơ'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='engine_type',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Loại động cơ đốt trong'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='exempt_initial_inspection',
            field=models.BooleanField(default=False, verbose_name='Miễn kiểm định lần đầu'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Loại nhiên liệu'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='has_child_detection',
            field=models.BooleanField(default=False, verbose_name='Có thiết bị cảnh báo trẻ em'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='has_driver_camera',
            field=models.BooleanField(default=False, verbose_name='Có camera người lái'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='has_passenger_camera',
            field=models.BooleanField(default=False, verbose_name='Có camera khoang chở khách'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='has_tachograph',
            field=models.BooleanField(default=False, verbose_name='Có thiết bị giám sát hành trình'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='inspection_qr_code',
            field=models.TextField(blank=True, default='', verbose_name='QR tra cứu chứng nhận'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='inspection_signer',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Người ký chứng nhận'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='inspection_stamp_issued',
            field=models.BooleanField(default=True, verbose_name='Được cấp tem kiểm định'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='inspection_station',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Cơ sở đăng kiểm'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='inspection_sticker_number',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Số seri tem kiểm định'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='inspection_verification_url',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='Website tra cứu đăng kiểm'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='lifetime_limit',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Niên hạn sử dụng'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='load_capacity_authorized',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Khối lượng hàng cho phép'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='load_capacity_design',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Khối lượng hàng theo thiết kế'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='lying_capacity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Số chỗ nằm'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='max_power',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Công suất lớn nhất'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='max_power_rpm',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Tốc độ quay công suất lớn nhất'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='modified_vehicle',
            field=models.BooleanField(default=False, verbose_name='Có cải tạo'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='overall_dimensions',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Kích thước bao'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='production_country',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Nước sản xuất'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='standing_capacity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Số chỗ đứng'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='tire_specification',
            field=models.TextField(blank=True, default='', verbose_name='Số lượng / cỡ lốp / trục'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='tire_tread',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Vết bánh xe'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='total_weight_authorized',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Khối lượng toàn bộ cho phép'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='total_weight_design',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Khối lượng toàn bộ theo thiết kế'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='towing_capacity_authorized',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Khối lượng kéo theo cho phép'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='towing_capacity_design',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Khối lượng kéo theo thiết kế'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_record_no',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Số quản lý'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='wheelbase',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Khoảng cách trục'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='wheelchair_capacity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Số xe lăn'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='badge_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='Phù hiệu có hiệu lực đến'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='badge_number',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Số phù hiệu'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='brand',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Nhãn hiệu / tên thương mại'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='chassis_number',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Số khung'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='color',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Màu sơn'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='engine_number',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Số động cơ'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='inspection_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='Đăng kiểm có hiệu lực đến'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='inspection_number',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Số giấy / số đăng kiểm'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='license_plate',
            field=models.CharField(max_length=30, unique=True, verbose_name='Biển số xe'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='load_capacity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Tải trọng'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Mã kiểu loại'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='notes',
            field=models.TextField(blank=True, default='', verbose_name='Ghi chú'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('active', 'Đang sử dụng'), ('inactive', 'Ngừng sử dụng'), ('repair', 'Đang sửa chữa'), ('liquidated', 'Đã thanh lý')], default='active', max_length=30, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='total_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Trọng lượng toàn bộ'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Loại phương tiện'),
        ),
    ]
