# Generated by Django 5.2.2 on 2026-02-02 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_reader_app', '0006_alter_invoice_fiscal_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='fiscal_year',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
