# Generated by Django 5.2.2 on 2026-09-14 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_reader_app', '0007_alter_vehicle_options_vehicle_cargo_dimensions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(max_length=50, unique=True, verbose_name='Mã nhân viên')),
                ('full_name', models.CharField(max_length=255, verbose_name='Họ và tên')),
                ('gender', models.CharField(blank=True, max_length=20, verbose_name='Giới tính')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Ngày sinh')),
                ('citizen_id', models.CharField(blank=True, max_length=20, verbose_name='CCCD')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Điện thoại')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.TextField(blank=True, verbose_name='Địa chỉ')),
                ('department', models.CharField(blank=True, max_length=255, verbose_name='Phòng ban')),
                ('position', models.CharField(blank=True, max_length=255, verbose_name='Chức vụ')),
                ('join_date', models.DateField(blank=True, null=True, verbose_name='Ngày vào làm')),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Mức lương')),
                ('status', models.CharField(choices=[('active', 'Đang làm việc'), ('inactive', 'Tạm nghỉ'), ('resigned', 'Đã nghỉ việc')], default='active', max_length=20, verbose_name='Trạng thái')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Nhân sự',
                'verbose_name_plural': 'Nhân sự',
                'db_table': 'employees',
                'ordering': ['employee_code'],
            },
        ),
        migrations.CreateModel(
            name='SocialInsurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_insurance_number', models.CharField(blank=True, max_length=50, verbose_name='Mã số BHXH')),
                ('social_insurance_book', models.CharField(blank=True, max_length=50, verbose_name='Số sổ BHXH')),
                ('health_insurance_number', models.CharField(blank=True, max_length=50, verbose_name='Số thẻ BHYT')),
                ('health_insurance_hospital', models.CharField(blank=True, max_length=255, verbose_name='Nơi KCB ban đầu')),
                ('insurance_start_date', models.DateField(blank=True, null=True, verbose_name='Ngày tham gia BHXH')),
                ('health_insurance_start', models.DateField(blank=True, null=True, verbose_name='BHYT từ ngày')),
                ('health_insurance_expiry', models.DateField(blank=True, null=True, verbose_name='BHYT đến ngày')),
                ('insurance_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Mức lương đóng BH')),
                ('position_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Phụ cấp chức vụ')),
                ('other_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Phụ cấp khác')),
                ('employee_social_rate', models.DecimalField(decimal_places=2, default=8, max_digits=5, verbose_name='Tỷ lệ NLĐ BHXH')),
                ('company_social_rate', models.DecimalField(decimal_places=2, default=17.5, max_digits=5, verbose_name='Tỷ lệ DN BHXH')),
                ('employee_health_rate', models.DecimalField(decimal_places=2, default=1.5, max_digits=5, verbose_name='Tỷ lệ NLĐ BHYT')),
                ('company_health_rate', models.DecimalField(decimal_places=2, default=3, max_digits=5, verbose_name='Tỷ lệ DN BHYT')),
                ('employee_unemployment_rate', models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='Tỷ lệ NLĐ BHTN')),
                ('company_unemployment_rate', models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='Tỷ lệ DN BHTN')),
                ('status', models.CharField(choices=[('active', 'Đang tham gia'), ('suspended', 'Tạm dừng'), ('stopped', 'Đã dừng')], default='active', max_length=20, verbose_name='Trạng thái')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='social_insurance', to='invoice_reader_app.employee', verbose_name='Nhân sự')),
            ],
            options={
                'verbose_name': 'BHXH',
                'verbose_name_plural': 'BHXH',
                'db_table': 'social_insurances',
                'ordering': ['employee__employee_code'],
            },
        ),
    ]
