# Generated by Django 5.2.2 on 2025-12-26 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_reader_app', '0007_bankpayment_bank_doc_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankpayment',
            name='related_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='summaries', to='invoice_reader_app.bankpayment'),
        ),
    ]
