# Generated by Django 5.2.2 on 2025-10-30 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_reader_app', '0007_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoice_reader_app.customer'),
        ),
    ]
