# Generated by Django 5.2.7 on 2026-04-01 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_reader_app', '0007_purchaseorder_fiscal_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankpayment',
            name='stt',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
