# Generated by Django 5.2.2 on 2026-09-14 17:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_reader_app', '0008_employee_socialinsurance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialinsurance',
            name='insurance_salary',
        ),
        migrations.RemoveField(
            model_name='socialinsurance',
            name='other_allowance',
        ),
        migrations.RemoveField(
            model_name='socialinsurance',
            name='position_allowance',
        ),
        migrations.AlterField(
            model_name='socialinsurance',
            name='company_health_rate',
            field=models.DecimalField(decimal_places=2, default=3, max_digits=5, verbose_name='Tỷ lệ DN BHYT (%)'),
        ),
        migrations.AlterField(
            model_name='socialinsurance',
            name='company_social_rate',
            field=models.DecimalField(decimal_places=2, default=17.5, max_digits=5, verbose_name='Tỷ lệ DN BHXH (%)'),
        ),
        migrations.AlterField(
            model_name='socialinsurance',
            name='company_unemployment_rate',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='Tỷ lệ DN BHTN (%)'),
        ),
        migrations.AlterField(
            model_name='socialinsurance',
            name='employee_health_rate',
            field=models.DecimalField(decimal_places=2, default=1.5, max_digits=5, verbose_name='Tỷ lệ NLĐ BHYT (%)'),
        ),
        migrations.AlterField(
            model_name='socialinsurance',
            name='employee_social_rate',
            field=models.DecimalField(decimal_places=2, default=8, max_digits=5, verbose_name='Tỷ lệ NLĐ BHXH (%)'),
        ),
        migrations.AlterField(
            model_name='socialinsurance',
            name='employee_unemployment_rate',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='Tỷ lệ NLĐ BHTN (%)'),
        ),
        migrations.CreateModel(
            name='SocialInsuranceSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_from', models.DateField(verbose_name='Áp dụng từ ngày')),
                ('effective_to', models.DateField(blank=True, null=True, verbose_name='Áp dụng đến ngày')),
                ('insurance_salary', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Mức lương đóng BHXH')),
                ('position_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Phụ cấp chức vụ')),
                ('other_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Phụ cấp khác')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('social_insurance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_histories', to='invoice_reader_app.socialinsurance', verbose_name='Hồ sơ BHXH')),
            ],
            options={
                'verbose_name': 'Mức đóng BHXH',
                'verbose_name_plural': 'Lịch sử mức đóng BHXH',
                'db_table': 'social_insurance_salaries',
                'ordering': ['-effective_from'],
            },
        ),
    ]
