# Generated by Django 5.2.2 on 2025-10-30 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_reader_app', '0008_invoiceitem_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='ten_goi_chung',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='ten_goi_xuat',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
