# Generated by Django 5.2.7 on 2025-11-06 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_reader_app', '0009_invoiceitem_ten_goi_chung_invoiceitem_ten_goi_xuat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoice_reader_app.invoice'),
        ),
    ]
