# Generated by Django 5.2.2 on 2026-09-14 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_reader_app', '0009_remove_socialinsurance_insurance_salary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialinsurance',
            name='company_health_rate',
        ),
        migrations.RemoveField(
            model_name='socialinsurance',
            name='company_social_rate',
        ),
        migrations.RemoveField(
            model_name='socialinsurance',
            name='company_unemployment_rate',
        ),
        migrations.RemoveField(
            model_name='socialinsurance',
            name='employee_health_rate',
        ),
        migrations.RemoveField(
            model_name='socialinsurance',
            name='employee_social_rate',
        ),
        migrations.RemoveField(
            model_name='socialinsurance',
            name='employee_unemployment_rate',
        ),
        migrations.CreateModel(
            name='InsuranceRateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_from', models.DateField(verbose_name='Áp dụng từ ngày')),
                ('effective_to', models.DateField(blank=True, null=True, verbose_name='Áp dụng đến ngày')),
                ('employee_social_rate', models.DecimalField(decimal_places=2, default=8, max_digits=5, verbose_name='NLĐ - BHXH (%)')),
                ('employee_health_rate', models.DecimalField(decimal_places=2, default=1.5, max_digits=5, verbose_name='NLĐ - BHYT (%)')),
                ('employee_unemployment_rate', models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='NLĐ - BHTN (%)')),
                ('company_social_rate', models.DecimalField(decimal_places=2, default=17.5, max_digits=5, verbose_name='DN - BHXH (%)')),
                ('company_health_rate', models.DecimalField(decimal_places=2, default=3, max_digits=5, verbose_name='DN - BHYT (%)')),
                ('company_unemployment_rate', models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='DN - BHTN (%)')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('social_insurance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_histories', to='invoice_reader_app.socialinsurance', verbose_name='Hồ sơ BHXH')),
            ],
            options={
                'verbose_name': 'Lịch sử tỷ lệ đóng',
                'verbose_name_plural': 'Lịch sử tỷ lệ đóng',
                'db_table': 'insurance_rate_histories',
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='InsuranceSalaryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_from', models.DateField(verbose_name='Áp dụng từ ngày')),
                ('effective_to', models.DateField(blank=True, null=True, verbose_name='Áp dụng đến ngày')),
                ('insurance_salary', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Mức lương đóng BH')),
                ('position_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Phụ cấp chức vụ')),
                ('other_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Phụ cấp khác')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('social_insurance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_histories', to='invoice_reader_app.socialinsurance', verbose_name='Hồ sơ BHXH')),
            ],
            options={
                'verbose_name': 'Lịch sử mức lương đóng BH',
                'verbose_name_plural': 'Lịch sử mức lương đóng BH',
                'db_table': 'insurance_salary_histories',
                'ordering': ['-effective_from'],
            },
        ),
        migrations.DeleteModel(
            name='SocialInsuranceSalary',
        ),
    ]
