# Generated by Django 5.2.2 on 2026-09-14 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_reader_app', '0010_remove_socialinsurance_company_health_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurancesalaryhistory',
            name='social_insurance',
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={},
        ),
        migrations.AlterModelOptions(
            name='insuranceratehistory',
            options={'ordering': ['-year']},
        ),
        migrations.AlterModelOptions(
            name='socialinsurance',
            options={},
        ),
        migrations.RemoveField(
            model_name='employee',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='insuranceratehistory',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='insuranceratehistory',
            name='effective_from',
        ),
        migrations.RemoveField(
            model_name='insuranceratehistory',
            name='effective_to',
        ),
        migrations.RemoveField(
            model_name='socialinsurance',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='socialinsurance',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='insuranceratehistory',
            name='insurance_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='insuranceratehistory',
            name='other_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='insuranceratehistory',
            name='position_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='insuranceratehistory',
            name='year',
            field=models.PositiveIntegerField(default=2026),
        ),
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='citizen_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='full_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='join_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(default='active', max_length=30),
        ),
        migrations.AlterField(
            model_name='insuranceratehistory',
            name='company_health_rate',
            field=models.DecimalField(decimal_places=2, default=3, max_digits=5),
        ),
        migrations.AlterField(
            model_name='insuranceratehistory',
            name='company_social_rate',
            field=models.DecimalField(decimal_places=2, default=17.5, max_digits=5),
        ),
        migrations.AlterField(
            model_name='insuranceratehistory',
            name='company_unemployment_rate',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name='insuranceratehistory',
            name='employee_health_rate',
            field=models.DecimalField(decimal_places=2, default=1.5, max_digits=5),
        ),
        migrations.AlterField(
            model_name='insuranceratehistory',
            name='employee_social_rate',
            field=models.DecimalField(decimal_places=2, default=8, max_digits=5),
        ),
        migrations.AlterField(
            model_name='insuranceratehistory',
            name='employee_unemployment_rate',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name='insuranceratehistory',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='insuranceratehistory',
            name='social_insurance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_histories', to='invoice_reader_app.socialinsurance'),
        ),
        migrations.AlterField(
            model_name='socialinsurance',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='social_insurance', to='invoice_reader_app.employee'),
        ),
        migrations.AlterField(
            model_name='socialinsurance',
            name='health_insurance_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='socialinsurance',
            name='health_insurance_hospital',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='socialinsurance',
            name='health_insurance_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='socialinsurance',
            name='health_insurance_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='socialinsurance',
            name='insurance_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='socialinsurance',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='socialinsurance',
            name='social_insurance_book',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='socialinsurance',
            name='social_insurance_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='socialinsurance',
            name='status',
            field=models.CharField(default='active', max_length=30),
        ),
        migrations.AddConstraint(
            model_name='insuranceratehistory',
            constraint=models.UniqueConstraint(fields=('social_insurance', 'year'), name='unique_insurance_rate_year'),
        ),
        migrations.AlterModelTable(
            name='employee',
            table=None,
        ),
        migrations.AlterModelTable(
            name='insuranceratehistory',
            table=None,
        ),
        migrations.AlterModelTable(
            name='socialinsurance',
            table=None,
        ),
        migrations.DeleteModel(
            name='InsuranceSalaryHistory',
        ),
    ]
