# Generated by Django 5.2.7 on 2025-11-06 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_reader_app', '0010_alter_invoiceitem_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='don_gia',
            field=models.FloatField(default=0),
        ),
    ]
