# Generated by Django 5.2.7 on 2026-04-09 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_reader_app', '0010_alter_invoiceitem_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='invoice_reader_app.invoice'),
        ),
    ]
