# Generated by Django 5.2.7 on 2026-04-09 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_reader_app', '0011_alter_purchaseorder_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankpayment',
            name='purchase_orders',
            field=models.ManyToManyField(blank=True, related_name='bank_payments', to='invoice_reader_app.purchaseorder'),
        ),
    ]
