# Generated by Django 5.2.2 on 2026-09-14 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_reader_app', '0011_remove_insurancesalaryhistory_social_insurance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceSalaryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True, verbose_name='Áp dụng đến ngày')),
                ('insurance_salary', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Mức lương đóng BH')),
                ('position_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Phụ cấp chức vụ')),
                ('other_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Phụ cấp khác')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Lịch sử mức lương đóng BH',
                'verbose_name_plural': 'Lịch sử mức lương đóng BH',
                'db_table': 'insurance_salary_histories',
                'ordering': ['-effective_from'],
            },
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['employee_code'], 'verbose_name': 'Nhân sự', 'verbose_name_plural': 'Nhân sự'},
        ),
        migrations.AlterModelOptions(
            name='insuranceratehistory',
            options={'ordering': ['-effective_from'], 'verbose_name': 'Lịch sử tỷ lệ đóng', 'verbose_name_plural': 'Lịch sử tỷ lệ đóng'},
        ),
        migrations.AlterModelOptions(
            name='socialinsurance',
            options={'ordering': ['employee__employee_code'], 'verbose_name': 'BHXH', 'verbose_name_plural': 'BHXH'},
        ),
        migrations.RemoveConstraint(
            model_name='insuranceratehistory',
            name='unique_insurance_rate_year',
        ),
        migrations.RemoveField(
            model_name='insuranceratehistory',
            name='insurance_salary',
        ),
        migrations.RemoveField(
            model_name='insuranceratehistory',
            name='other_allowance',
        ),
        migrations.RemoveField(
            model_name='insuranceratehistory',
            name='position_allowance',
        ),
        migrations.RemoveField(
            model_name='insuranceratehistory',
            name='year',
        ),
        migrations.AddField(
            model_name='employee',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='insuranceratehistory',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='insuranceratehistory',
            name='effective_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='insuranceratehistory',
            name='effective_to',
            field=models.DateField(blank=True, null=True, verbose_name='Áp dụng đến ngày'),
        ),
        migrations.AddField(
            model_name='socialinsurance',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socialinsurance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.TextField(blank=True, verbose_name='Địa chỉ'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='citizen_id',
            field=models.CharField(blank=True, max_length=20, verbose_name='CCCD'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày sinh'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(blank=True, max_length=255, verbose_name='Phòng ban'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Mã nhân viên'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='Họ và tên'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(blank=True, max_length=20, verbose_name='Giới tính'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='join_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày vào làm'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Ghi chú'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Điện thoại'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(blank=True, max_length=255, verbose_name='Chức vụ'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Mức lương'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('active', 'Đang làm việc'), ('inactive', 'Tạm nghỉ'), ('resigned', 'Đã nghỉ việc')], default='active', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='insuranceratehistory',
            name='company_health_rate',
            field=models.DecimalField(decimal_places=2, default=3, max_digits=5, verbose_name='DN - BHYT (%)'),
        ),
        migrations.AlterField(
            model_name='insuranceratehistory',
            name='company_social_rate',
            field=models.DecimalField(decimal_places=2, default=17.5, max_digits=5, verbose_name='DN - BHXH (%)'),
        ),
        migrations.AlterField(
            model_name='insuranceratehistory',
            name='company_unemployment_rate',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='DN - BHTN (%)'),
        ),
        migrations.AlterField(
            model_name='insuranceratehistory',
            name='employee_health_rate',
            field=models.DecimalField(decimal_places=2, default=1.5, max_digits=5, verbose_name='NLĐ - BHYT (%)'),
        ),
        migrations.AlterField(
            model_name='insuranceratehistory',
            name='employee_social_rate',
            field=models.DecimalField(decimal_places=2, default=8, max_digits=5, verbose_name='NLĐ - BHXH (%)'),
        ),
        migrations.AlterField(
            model_name='insuranceratehistory',
            name='employee_unemployment_rate',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='NLĐ - BHTN (%)'),
        ),
        migrations.AlterField(
            model_name='insuranceratehistory',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Ghi chú'),
        ),
        migrations.AlterField(
            model_name='insuranceratehistory',
            name='social_insurance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_histories', to='invoice_reader_app.socialinsurance', verbose_name='Hồ sơ BHXH'),
        ),
        migrations.AlterField(
            model_name='socialinsurance',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='social_insurance', to='invoice_reader_app.employee', verbose_name='Nhân sự'),
        ),
        migrations.AlterField(
            model_name='socialinsurance',
            name='health_insurance_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='BHYT đến ngày'),
        ),
        migrations.AlterField(
            model_name='socialinsurance',
            name='health_insurance_hospital',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nơi KCB ban đầu'),
        ),
        migrations.AlterField(
            model_name='socialinsurance',
            name='health_insurance_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Số thẻ BHYT'),
        ),
        migrations.AlterField(
            model_name='socialinsurance',
            name='health_insurance_start',
            field=models.DateField(blank=True, null=True, verbose_name='BHYT từ ngày'),
        ),
        migrations.AlterField(
            model_name='socialinsurance',
            name='insurance_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày tham gia BHXH'),
        ),
        migrations.AlterField(
            model_name='socialinsurance',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Ghi chú'),
        ),
        migrations.AlterField(
            model_name='socialinsurance',
            name='social_insurance_book',
            field=models.CharField(blank=True, max_length=50, verbose_name='Số sổ BHXH'),
        ),
        migrations.AlterField(
            model_name='socialinsurance',
            name='social_insurance_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Mã số BHXH'),
        ),
        migrations.AlterField(
            model_name='socialinsurance',
            name='status',
            field=models.CharField(choices=[('active', 'Đang tham gia'), ('suspended', 'Tạm dừng'), ('stopped', 'Đã dừng')], default='active', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AlterModelTable(
            name='employee',
            table='employees',
        ),
        migrations.AlterModelTable(
            name='insuranceratehistory',
            table='insurance_rate_histories',
        ),
        migrations.AlterModelTable(
            name='socialinsurance',
            table='social_insurances',
        ),
        migrations.AddField(
            model_name='insurancesalaryhistory',
            name='social_insurance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_histories', to='invoice_reader_app.socialinsurance', verbose_name='Hồ sơ BHXH'),
        ),
    ]
