# Generated by Django 5.2.7 on 2025-11-06 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_reader_app', '0011_alter_invoiceitem_don_gia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='thanh_tien',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='thanh_toan',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='tien_thue',
            field=models.FloatField(default=0),
        ),
    ]
