# Generated by Django 5.2.2 on 2026-09-15 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_reader_app', '0012_insurancesalaryhistory_alter_employee_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='da_tao_px',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Đã tạo phiếu xuất'),
        ),
    ]
