# Generated by Django 5.2.2 on 2026-09-29 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_reader_app', '0013_invoice_da_tao_px'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField(verbose_name='Ngày')),
                ('content', models.TextField(verbose_name='Nội dung công việc')),
                ('process_content', models.TextField(blank=True, default='', verbose_name='Nội dung xử lý')),
                ('status', models.CharField(choices=[('pending', 'Đang xử lý'), ('completed', 'Hoàn thành')], db_index=True, default='pending', max_length=20, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày hoàn thành')),
                ('handler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Người xử lý')),
            ],
            options={
                'verbose_name': 'Công việc',
                'verbose_name_plural': 'Công việc',
                'ordering': ['-work_date', '-id'],
                'indexes': [models.Index(fields=['work_date'], name='invoice_rea_work_da_48daa5_idx'), models.Index(fields=['status'], name='invoice_rea_status_45549e_idx'), models.Index(fields=['handler'], name='invoice_rea_handler_014a14_idx')],
            },
        ),
    ]
