# Generated by Django 5.2.7 on 2025-11-07 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_reader_app', '0013_alter_invoiceitem_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_hang', models.CharField(max_length=255)),
                ('ten_goi_chung', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
