# Generated by Django 5.2.2 on 2026-04-13 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_reader_app', '0013_accountsystem_accountgroup_account_journalentry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='mst_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='mst_image',
            field=models.ImageField(blank=True, null=True, upload_to='mst/'),
        ),
    ]
