# Generated by Django 5.2.7 on 2025-11-07 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_reader_app', '0014_productname'),
    ]

    operations = [
        migrations.AddField(
            model_name='productname',
            name='ten_goi_xuat',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
