# Generated by Django 5.2.7 on 2025-11-10 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_reader_app', '0015_productname_ten_goi_xuat'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='sku',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productname',
            name='sku',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
