# Generated by Django 5.2.2 on 2026-04-13 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_reader_app', '0015_customer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='ten_viet_tat',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
