# Generated by Django 5.2.1 on 2026-05-27 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_reader_app', '0016_customer_ten_viet_tat'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='fiscal_year',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
