# Generated by Django 5.2.2 on 2025-11-11 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_reader_app', '0017_purchaseorder_purchaseorderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='thue_suat_field',
            field=models.DecimalField(decimal_places=2, default=0.08, max_digits=4),
            preserve_default=False,
        ),
    ]
