# Generated by Django 5.2.1 on 2026-05-27 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_reader_app', '0017_purchaseorder_fiscal_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='phan_loai_phieu',
            field=models.CharField(choices=[('HH', 'Hàng hóa'), ('PN', 'Phiếu nhập'), ('PX', 'Phiếu xuất'), ('KH', 'Khác')], default='HH', max_length=2, verbose_name='Phân loại phiếu'),
        ),
    ]
