# Generated by Django 5.2.2 on 2025-11-11 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_reader_app', '0018_purchaseorderitem_thue_suat_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='tien_thue_field',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='thue_suat_field',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
