# Generated by Django 5.2.1 on 2026-07-09 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_reader_app', '0019_cashreceipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashreceipt',
            name='receipt_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
