# Generated by Django 5.2.2 on 2025-11-11 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_reader_app', '0019_purchaseorderitem_tien_thue_field_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='thue_suat_field',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
