# Generated by Django 5.2.2 on 2026-07-09 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_reader_app', '0020_cashreceipt_receipt_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankpayment',
            name='cash_deposit',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='bankpayment',
            name='interest_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18),
        ),
    ]
