# Generated by Django 5.2.2 on 2026-07-09 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_reader_app', '0021_bankpayment_cash_deposit_bankpayment_interest_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankpayment',
            name='source_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='summary_records', to='invoice_reader_app.bankpayment'),
        ),
    ]
