# Generated by Django 5.2.7 on 2025-11-12 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_reader_app', '0021_remove_purchaseorder_status_purchaseorder_total_tax_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoice_reader_app.invoice'),
        ),
    ]
