# Generated by Django 5.2.7 on 2025-11-12 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_reader_app', '0022_alter_purchaseorder_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='invoice_reader_app.invoice'),
        ),
    ]
