# Generated by Django 5.2.2 on 2026-07-09 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_reader_app', '0022_bankpayment_source_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankpayment',
            name='parent_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='summary_children', to='invoice_reader_app.bankpayment'),
        ),
    ]
