# Generated by Django 5.2.2 on 2026-07-12 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_reader_app', '0023_bankpayment_parent_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankPaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_amount', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='invoice_reader_app.bankpayment')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='invoice_reader_app.purchaseorder')),
            ],
        ),
    ]
