# Generated by Django 5.2.2 on 2025-11-12 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_reader_app', '0024_alter_invoiceitem_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='sku',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='ten_goi_chung',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
