# Generated by Django 5.2.1 on 2026-07-13 06:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_reader_app', '0024_bankpaymentallocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankpayment',
            name='logic_version',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='bankpaymentallocation',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='bankpaymentallocation',
            name='logic_version',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='bankpaymentallocation',
            unique_together={('payment', 'purchase_order')},
        ),
    ]
