# Generated by Django 5.2.7 on 2025-11-13 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_reader_app', '0025_purchaseorderitem_sku_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='phan_loai_phieu',
            field=models.CharField(choices=[('HH', 'Hàng hóa'), ('KH', 'Khác')], default='HH', max_length=2, verbose_name='Phân loại phiếu'),
        ),
    ]
