# Generated by Django 5.2.1 on 2026-07-13 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_reader_app', '0025_bankpayment_logic_version_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankpaymentallocation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
