# Generated by Django 5.2.2 on 2026-07-15 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_reader_app', '0026_alter_bankpaymentallocation_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankpayment',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoice_reader_app.customer'),
        ),
    ]
