# Generated by Django 5.2.7 on 2025-11-13 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_reader_app', '0026_purchaseorder_phan_loai_phieu'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
