# Generated by Django 5.2.7 on 2025-11-13 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_reader_app', '0027_purchaseorderitem_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
