# Generated by Django 5.2.7 on 2025-11-13 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_reader_app', '0028_invoiceitem_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='active',
        ),
    ]
