# Generated by Django 5.2.7 on 2025-11-13 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_reader_app', '0029_remove_purchaseorderitem_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='po_item_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
