# Generated by Django 5.2.7 on 2025-11-14 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_reader_app', '0030_invoiceitem_po_item_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='ngay_hd',
            field=models.DateField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together={('so_hoa_don', 'ky_hieu', 'ma_so_thue', 'ngay_hd', 'loai_hd')},
        ),
    ]
