# Generated by Django 5.2.2 on 2025-11-16 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_reader_app', '0031_alter_invoice_unique_together_alter_invoice_ngay_hd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='is_export',
            field=models.BooleanField(default=False),
        ),
    ]
