# Generated by Django 5.2.2 on 2025-11-16 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_reader_app', '0032_purchaseorderitem_is_export'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='invoice_reader_app.invoice'),
        ),
    ]
