# Generated by Django 5.2.2 on 2025-11-16 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_reader_app', '0033_alter_purchaseorder_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='so_luong_quy_doi',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
