# Generated by Django 5.2.7 on 2025-11-19 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_reader_app', '0035_alter_purchaseorderitem_so_luong_quy_doi'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='chiet_khau',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
    ]
