# Generated by Django 5.2.7 on 2025-11-20 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_reader_app', '0036_invoiceitem_chiet_khau'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='don_gia',
            field=models.DecimalField(decimal_places=4, max_digits=18),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='so_luong',
            field=models.DecimalField(decimal_places=4, max_digits=18),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='thanh_tien',
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='thanh_toan',
            field=models.DecimalField(decimal_places=4, max_digits=18),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='tien_thue',
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
    ]
