# Generated by Django 5.2.7 on 2025-11-20 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_reader_app', '0038_alter_invoiceitem_don_gia_alter_invoiceitem_so_luong_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='don_gia_trước_ck',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
    ]
