# Generated by Django 5.2.7 on 2025-11-20 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_reader_app', '0039_invoiceitem_don_gia_trước_ck'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoiceitem',
            old_name='don_gia_trước_ck',
            new_name='don_gia_ck',
        ),
    ]
