# Generated by Django 5.2.7 on 2025-11-20 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_reader_app', '0040_rename_don_gia_trước_ck_invoiceitem_don_gia_ck'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceitem',
            name='don_gia_ck',
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='don_gia',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='so_luong',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='thanh_tien',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='thanh_toan',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='thue_suat',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='tien_thue',
            field=models.FloatField(default=0),
        ),
    ]
