# Generated by Django 5.2.7 on 2025-11-20 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_reader_app', '0041_remove_invoiceitem_don_gia_ck_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='don_gia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='so_luong',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='thanh_tien',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='thanh_toan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='tien_thue',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
