# Generated by Django 5.2.7 on 2025-11-20 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_reader_app', '0042_alter_invoiceitem_don_gia_alter_invoiceitem_so_luong_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='don_gia',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='dvt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='so_luong',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='thanh_tien',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='thanh_toan',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='tien_thue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
    ]
