# Generated by Django 5.2.7 on 2025-11-20 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_reader_app', '0043_alter_invoiceitem_don_gia_alter_invoiceitem_dvt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='dvt',
            field=models.CharField(max_length=200),
        ),
    ]
