# Generated by Django 5.2.7 on 2025-11-24 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_reader_app', '0044_alter_invoiceitem_dvt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='thue_suat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
