# Generated by Django 5.2.7 on 2025-11-25 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_reader_app', '0046_invoiceitem_nhom_hang'),
    ]

    operations = [
        migrations.AddField(
            model_name='productname',
            name='nhom_hang',
            field=models.CharField(blank=True, choices=[('son_nuoc', 'Sơn nước'), ('son_dau', 'Sơn dầu'), ('chat_mau', 'Chất màu'), ('chong_tham', 'Chống thấm')], max_length=30, null=True),
        ),
    ]
