# Generated by Django 5.2.7 on 2025-12-01 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_reader_app', '0048_bankpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankpayment',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
