# Generated by Django 5.2.7 on 2025-12-01 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_reader_app', '0049_bankpayment_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankpayment',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoice_reader_app.purchaseorder'),
        ),
    ]
