# Generated by Django 5.2.7 on 2025-12-01 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_reader_app', '0050_alter_bankpayment_purchase_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankpayment',
            name='balance',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='bankpayment',
            name='credit',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='bankpayment',
            name='debit',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='bankpayment',
            name='doc_no',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='bankpayment',
            name='stt',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='bankpayment',
            name='amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='bankpayment',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoice_reader_app.purchaseorder'),
        ),
    ]
