# Generated by Django 5.2.2 on 2025-12-01 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_reader_app', '0051_bankpayment_balance_bankpayment_credit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankpayment',
            name='purchase_order',
        ),
        migrations.AddField(
            model_name='bankpayment',
            name='purchase_orders',
            field=models.ManyToManyField(blank=True, to='invoice_reader_app.purchaseorder'),
        ),
    ]
