# Generated by Django 5.2.2 on 2025-12-01 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_reader_app', '0052_remove_bankpayment_purchase_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankpayment',
            name='purchase_orders',
        ),
        migrations.AddField(
            model_name='bankpayment',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoice_reader_app.purchaseorder'),
        ),
    ]
