# Generated by Django 5.2.7 on 2025-12-02 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_reader_app', '0054_remove_bankpayment_purchase_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='tong_tien',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20),
        ),
    ]
