# Generated by Django 5.2.7 on 2025-12-03 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_reader_app', '0055_alter_invoice_tong_tien'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='chiet_khau',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='thanh_tien_sau_ck',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='thanh_toan_field',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='tong_tien',
            field=models.FloatField(default=0),
        ),
    ]
