# Generated by Django 5.2.7 on 2025-12-03 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_reader_app', '0056_purchaseorderitem_chiet_khau_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='thanh_tien',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
    ]
